import type { Product, Category } from "./types"

export const categories: Category[] = [
  {
    id: "capacetes",
    name: "Capacetes",
    icon: "🪖",
    subcategories: ["Integral", "Aberto", "Modular", "Off-Road"],
  },
  {
    id: "pecas",
    name: "Peças",
    icon: "⚙️",
    subcategories: ["Motor", "Freios", "Suspensão", "Elétrica"],
  },
  {
    id: "acessorios",
    name: "Acessórios",
    icon: "🧰",
    subcategories: ["Luvas", "Jaquetas", "Botas", "Bolsas"],
  },
  {
    id: "equipamentos",
    name: "Equipamentos",
    icon: "🦺",
    subcategories: ["Proteção", "Comunicação", "Iluminação"],
  },
  {
    id: "manutencao",
    name: "Manutenção",
    icon: "🔧",
    subcategories: ["Óleos", "Ferramentas", "Limpeza"],
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Capacete X-Lite X-803 RS Ultra Carbon",
    description:
      "Capacete racing de alta performance com calota em fibra de carbono. Aerodinâmica otimizada e sistema de ventilação avançado.",
    price: 3499.9,
    category: "capacetes",
    images: [
      "/capacete-moto-racing-vermelho-carbono.jpg",
      "/capacete-moto-racing-lateral.jpg",
      "/capacete-moto-racing-interior.jpg",
      "/capacete-moto-racing-traseira.jpg",
    ],
    rating: 4.8,
    reviewCount: 127,
    inStock: true,
    specifications: {
      size: ["PP", "P", "M", "G", "GG"],
      weight: "1.250kg",
      material: "Fibra de Carbono",
      color: ["Vermelho", "Preto", "Branco"],
    },
  },
  {
    id: "2",
    name: "Disco de Freio Dianteiro Brembo",
    description: "Disco de freio flutuante de alta performance. Compatível com modelos esportivos.",
    price: 899.9,
    category: "pecas",
    images: ["/disco-freio-moto-brembo.jpg", "/disco-freio-moto-detalhe.jpg"],
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    specifications: {
      material: "Aço Inox",
      weight: "2.1kg",
    },
  },
  {
    id: "3",
    name: "Jaqueta Alpinestars GP Pro V2",
    description: "Jaqueta em couro premium com proteções certificadas. Design aerodinâmico e ventilação estratégica.",
    price: 2799.9,
    category: "acessorios",
    images: ["/jaqueta-moto-couro-racing-vermelha.jpg", "/jaqueta-moto-couro-costas.jpg", "/jaqueta-moto-couro-protecoes.jpg"],
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    specifications: {
      size: ["P", "M", "G", "GG", "XG"],
      material: "Couro Bovino Premium",
      color: ["Preto/Vermelho", "Preto/Branco"],
    },
  },
  {
    id: "4",
    name: "Luvas Dainese Full Metal 6",
    description: "Luvas racing com proteção em titânio e fibra de carbono. Máxima proteção e sensibilidade.",
    price: 1299.9,
    category: "acessorios",
    images: ["/luvas-moto-racing-carbono.jpg", "/luvas-moto-racing-protecao.jpg"],
    rating: 4.9,
    reviewCount: 203,
    inStock: true,
    specifications: {
      size: ["P", "M", "G", "GG"],
      material: "Couro + Carbono",
      color: ["Preto", "Preto/Vermelho"],
    },
  },
  {
    id: "5",
    name: "Escapamento Akrapovic Racing",
    description: "Sistema de escapamento completo em titânio. Redução de peso e ganho de performance.",
    price: 8999.9,
    category: "pecas",
    images: ["/escapamento-moto-titanio-akrapovic.jpg", "/escapamento-moto-instalado.jpg"],
    rating: 5.0,
    reviewCount: 67,
    inStock: true,
    specifications: {
      material: "Titânio",
      weight: "3.2kg",
    },
  },
  {
    id: "6",
    name: "Óleo Motul 300V 10W40",
    description: "Óleo sintético de alta performance para motores de competição.",
    price: 189.9,
    category: "manutencao",
    images: ["/oleo-motul-300v-moto.jpg", "/oleo-motor-sintetico.jpg"],
    rating: 4.8,
    reviewCount: 412,
    inStock: true,
    specifications: {
      weight: "4L",
    },
  },
  {
    id: "7",
    name: "Capacete Shoei NXR2",
    description: "Capacete touring premium com excelente isolamento acústico e conforto.",
    price: 2899.9,
    category: "capacetes",
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    rating: 4.9,
    reviewCount: 234,
    inStock: true,
    specifications: {
      size: ["PP", "P", "M", "G", "GG"],
      weight: "1.450kg",
      material: "AIM+",
      color: ["Preto", "Branco", "Cinza"],
    },
  },
  {
    id: "8",
    name: "Botas TCX RT-Race Pro Air",
    description: "Botas racing com proteções certificadas e sistema de ventilação.",
    price: 1899.9,
    category: "acessorios",
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    rating: 4.7,
    reviewCount: 98,
    inStock: true,
    specifications: {
      size: ["38", "39", "40", "41", "42", "43", "44", "45"],
      material: "Microfibra + Couro",
      color: ["Preto", "Preto/Vermelho", "Branco"],
    },
  },
]
